import type { Cards, OwnedCharacter } from '@shared'

export function makeCards(
    _chosen: OwnedCharacter[] = [],
    _username: string
): Cards {
    return {
        draw: {
            uuid1: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
        },
        hand: {
            uuid21: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid22: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid23: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid24: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid25: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid26: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid27: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid28: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid29: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid210: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid211: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
            uuid212: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
        },
        discard: {
            uuid3: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
        },
        removed: {
            uuid3: {
                name: 'string',
                url: './Sweep The Leg.png',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterClass: 'string',
                deckId: 'string',
            },
        },
    }
}
