#!/bin/bash

set -euo pipefail # strict mode

# Add npm binaries to path
export PATH=./node_modules/.bin:$PATH

# declare -a validCommands

## ROOT

function install-all() {
    pnpm i
}

function CI() {
    set +e
    source ~/.bashrc
    pnpm i -P
    production=yes client:build
    production=yes server:build
}

function lint() {
    eslint . --cache
}

function clean-tsc-all() {
    rm -rf **/dist **/tsconfig.tsbuildinfo
    tsc-all
}

function tsc-all() {
    tsc -b .
}

function build-all() {
    node scripts/buildAll.mjs
}

function fmt() {
    generate-indices
    prettier-no-jsx-parens -w -l .
    eslint . --fix --cache
}

# sorts the directories in the project by the number of files in each
function biggest-dirs() {
    set +x
    fd -t d | while read -r line; do echo $(ls "$line" | wc -l) $line; done | sort -n
}

function mp4-to-webm() {
    path=$1
    ffmpeg -i $1.mp4 -c:v libvpx-vp9 -crf 30 -b:v 0 -b:a 128k -c:a libopus $1.webm
}

function png-to-webp() {
    path=$1
    mogrify -format webp $1.png
}

function generate-indices() {
    # vscode-generate-index-standalone '!node_modules/' server client game shared '!node_modules/'
    # vscode-generate-index-standalone './shared/**/*.ts' '!**/node_modules' './client/**/*.ts' '!**/node_modules' './game/**/*.ts' '!**/node_modules' './server/**/*.ts' '!**/node_modules'

    vscode-generate-index-standalone './shared/**/*.ts' '!**/node_modules'
    vscode-generate-index-standalone './client/**/*.ts' '!**/node_modules'
    vscode-generate-index-standalone './game/**/*.ts' '!**/node_modules'
    vscode-generate-index-standalone './server/**/*.ts' '!**/node_modules'
}

function save-staged() {
    bash scripts/savestaged.sh
}

function new-todo() {
    git diff origin/main -G TODO
}

function clean-branches() {
    git branch -D $(git branch | grep -v 'main')
    git fetch
    git pull
    git remote prune origin
}

function lint-watch() {
    echo 'doesnt work great'
    esw -w server/**/*.ts client/**/*.ts{,x} shared/**/*.ts
}

function view-imports-exports() {
    ag --nonumbers --only-matching --group 'import.*$|(export [A-z]+ [A-z]+)' . >imports-and-exports.ignore.txt
}

function exports() {
    dir=$1

    ag --ts --nogroup '^export [A-z]+ [A-z]+' $dir | sed -e 's/export /,/' | column -t -s,
}

function arkit() {
    npx arkit
}

# generate the full dependency graph
function dep-graph-full() {
    rm -f dep-graph.svg
    depcruise --output-type=dot --ts-config=tsconfig.json . --exclude node_modules |
        dot -T svg >dep-graph.svg
    open dep-graph.svg
}

# generate the dependency graph in a given subdirectory
function dep-graph() {
    subdir=$1
    dashed=${subdir//\//-}
    name="dep-graph-$dashed.svg"
    rm -f $name
    depcruise $subdir --output-type=dot --include-only="^$subdir" --exclude=node_modules |
        dot -T svg >$name
    open $name
}

function dep-graph-package() {
    package=$1
    cd $package
    rm -f dep-graph.svg
    depcruise . --output-type=dot --ts-config tsconfig.json --exclude 'node_modules|@|shared' |
        dot -T svg >dep-graph.svg
    open dep-graph.svg
}

function npm-clean() {
    rm -rf pnpm-lock.yaml node_modules **/node_modules
}

## CLIENT

function client:build() {
    node scripts/clientEsbuild.mjs
}
function client:build-watch() {
    node scripts/clientEsbuild.mjs watch
}
function client:bare-build-watch() {
    BARE=yes client:build-watch
}
function client:tsc() {
    tsc --build client
}
function client:live-serve() {
    live-server builds/client --host=localhost --port=3000
}

## GAME (no has storage only memory <3)
function game:build() {
    cd game && npm run build
}

## MAIN SERVER

function server:digitalocean() {
    node builds/server.js
}
function server:server() {
    DEV_STATIC_ASSETS=yes node --enable-source-maps builds/server.js
}
function server:server-watch() {
    DEV_STATIC_ASSETS=yes nodemon --enable-source-maps --watch builds/server.js builds/server.js
}
function server:server-watch-debug() {
    DEV_STATIC_ASSETS=yes nodemon --inspect --enable-source-maps --watch builds/server.js builds/server.js
}
function server:build() {
    node scripts/serverEsbuild.mjs
}
function server:build-watch() {
    node scripts/serverEsbuild.mjs watch
}
function server:tsc() {
    tsc -b server
}

set -x # print commands as executed
eval "$@"
