import type { ServerActions } from 'shared'

export const generateGameAction: ServerActions['generateGame'] = async ({ userId, worldPrompt, stylePrompt }) => {
  const world = (worldPrompt || 'mysterious land').trim()
  const style = (stylePrompt || 'vibrant').trim()
  const name = `AI: ${world.split(' ').slice(0, 3).join(' ')} ${style.split(' ')[0]}`
  const desc = `A ${style} world where ${world}. Unique Kaiju, cards, and mechanics generated by Grok.`

  // In real: call xAI Grok text gen + image_gen API, save asset, update rulebook/compendium
  const cards = [
    { id: 'gen-slash', name: `${world.split(' ')[0]} Fury`, desc: `Deal extra in ${style} style.` },
    { id: 'gen-echo', name: 'World Pulse', desc: `Chain based on generated stance.` }
  ]

  // Placeholder image - real would be new Grok Imagine result
  const image = '/assets/generated/grok-generated-kaiju.jpg'

  console.log(`[generateGame] for ${userId}: world="${world}" style="${style}"`)

  return { name, desc, cards, image }
}
