// @index('./*', f => `export { ${f.name} } from '${f.path}'`)
export { setInitialGameState } from './setInitialGameState'
export { loadGameState } from './loadGameState'
export { login } from './login'
export { startRun } from './startRun'
export { getCurrentRun } from './getCurrentRun'
export { endRun } from './endRun'
export { getNumKaijuInGoodEarth } from './getNumKaijuInGoodEarth'
export { getSchema } from './getSchema'
export { getLeaderboard } from './getLeaderboard'
export { getLeaderboardEntryCount } from './getLeaderboardEntryCount'
export { setUsername } from './setUsername'
export { authenticateWeb3User } from './authenticateWeb3User'
export { authenticateGuestUser } from './authenticateGuestUser'
export { verifyAuthToken } from './verifyAuthToken'
// @endindex
