import type { CardDefinition, CardId } from 'shared'

const basicMagicAttackBase = {
    name: 'Magic Attack',
    energy: 1,
    targetNum: 1,
    targetType: 'enemies',
    actions: 'deal(wisdom)',
    type: 'attack',
} as const
const basicAttackBase = {
    name: 'Attack',
    energy: 1,
    targetNum: 1,
    targetType: 'enemies',
    actions: 'deal(strength)',
    type: 'attack',
} as const
const blockBase = {
    name: 'Shield',
    energy: 1,
    targetNum: 1,
    targetType: 'friends',
    actions: 'addBlock(defense)',
    type: 'defense',
} as const
/** Enforces correct self-id */
type CardDefinitionsMap = {
    [Id in CardId]: CardDefinition & { id: Id }
}
export const cardDefinitionsMap: CardDefinitionsMap = {
    TEST_turnStartEffects: {
        name: 'TEST: megableed!!',
        id: 'TEST_turnStartEffects',
        energy: 0,
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'chain(effect("bleed", 2), effect("poison", 4), effect("passiveBlock", 2))',
        type: 'attack',
        characterClass: 'knight',
    },
    shield: {
        name: 'Shield',
        energy: 1,
        id: 'shield',
        targetNum: 1,
        targetType: 'friends',
        actions: 'addBlock(defense + 2)',
        type: 'defense',
        characterClass: 'knight',
    },
    shieldOfLight: {
        name: 'Shield of Light',
        energy: 1,
        id: 'shieldOfLight',
        targetNum: 1,
        targetType: 'friends',
        actions: 'addBlock(wisdom * 1.5)',
        type: 'defense',
        characterClass: 'cleric',
    },
    sweepTheLeg: {
        name: 'Sweep The Leg',
        energy: 2,
        id: 'sweepTheLeg',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'chain(deal(strength), effect("debilitated",1))',
        type: 'attack',
        characterClass: 'knight',
    },
    bodySlam: {
        name: 'Shield Bash',
        energy: 1,
        id: 'bodySlam',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'chain(deal(block), "(equal to block)")', // , dwindle()
        type: 'attack',
        characterClass: 'knight',
    },
    jab: {
        name: 'Jab',
        energy: 0,
        id: 'jab',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'strengthy = strength * .5; deal(strengthy)',
        type: 'attack',
        characterClass: 'bard',
    },
    strike: {
        name: 'Attack',
        energy: 1,
        id: 'strike',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'deal(strength)',
        type: 'attack',
        characterClass: 'knight',
    },
    orbOfLightning: {
        name: 'Orb of Lightning',
        energy: 1,
        id: 'orbOfLightning',
        targetNum: 1,
        targetType: 'self',
        actions: 'orb("lightning", 3)',
        type: 'enchantment',
        characterClass: 'wizard',
    },
    orbOfProtection: {
        name: 'Orb of Protection',
        energy: 1,
        id: 'orbOfProtection',
        targetNum: 1,
        targetType: 'self',
        actions: 'orb("protection", 3)',
        type: 'enchantment',
        characterClass: 'wizard',
    },
    basicAttackWizard: {
        ...basicMagicAttackBase,
        id: 'basicAttackWizard',
        characterClass: 'wizard',
    },
    basicAttackBard: {
        ...basicMagicAttackBase,
        id: 'basicAttackBard',
        characterClass: 'bard',
    },
    magicRitual: {
        name: 'Magic Ritual',
        energy: 0,
        id: 'magicRitual',
        targetNum: 1,
        targetType: 'self',
        actions: 'chain(addEnergy(2), momentary())',
        type: 'utility',
        characterClass: 'wizard',
    },
    chainLightning: {
        name: 'Chain Lightning',
        energy: 2,
        id: 'chainLightning',
        targetNum: 3,
        targetType: 'enemies',
        actions: 'deal(0.75 * wisdom, 3)',
        type: 'attack',
        characterClass: 'wizard',
    },
    spellBook: {
        name: 'Spell Book',
        energy: 3,
        id: 'spellBook',
        targetNum: 1,
        targetType: 'self',
        actions: 'chain(addEnergyPerRound(1), momentary())',
        type: 'enchantment',
        characterClass: 'wizard',
    },
    fireball: {
        name: 'Fireball',
        energy: 2,
        id: 'fireball',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'deal(wisdom * 2.5)',
        type: 'attack',
        characterClass: 'wizard',
    },
    /**Target Attack Card, enchantment or ~~token~~ orb doubles the amount of damage it deals this turn. */
    arcanePower: {
        name: 'Arcane Power',
        energy: 1,
        id: 'arcanePower',
        targetNum: 1,
        targetType: ['orb', 'cardAttack', 'cardEnchantment'],
        actions: 'doubleEnchantmentOrToken()',
        type: 'utility',
        characterClass: 'wizard',
    },
    scatterBrained: {
        name: 'Scatter Brained',
        energy: 1,
        id: 'scatterBrained',
        targetNum: 0,
        targetType: 'self',
        actions: 'chain(draw(3), require("discardHand", 2, 2))',
        type: 'utility',
        characterClass: 'wizard',
    },
    trance: {
        name: 'Trance',
        energy: 1,
        id: 'trance',
        targetNum: 0,
        targetType: 'self',
        actions: 'chain(effect("trance", 3), momentary())',
        type: 'utility',
        characterClass: 'wizard',
    },
    // coldTrance: {
    //     name: 'Super Trance',
    //     energy: 1,
    //     id: 'trance',
    //     targetNum: 0,
    //     targetType: 'self',
    //     actions: 'chain(effect("trance", 2), orb("frost", 2))',
    //     type: 'utility',
    //     characterClass: 'wizard',
    // },
    orbOfFrost: {
        name: 'Orb of Frost',
        energy: 1,
        id: 'orbOfFrost',
        targetNum: 1,
        targetType: 'self',
        actions: 'orb("frost", 3)',
        type: 'enchantment',
        characterClass: 'wizard',
    },
    basicAttackKnight: {
        ...basicAttackBase,
        id: 'basicAttackKnight',
        characterClass: 'knight',
    },
    basicAttackCleric: {
        ...basicAttackBase,
        id: 'basicAttackCleric',
        characterClass: 'cleric',
    },
    basicAttackRogue: {
        ...basicAttackBase,
        id: 'basicAttackRogue',
        characterClass: 'rogue',
    },
    blockKnight: {
        ...blockBase,
        id: 'blockKnight',
        characterClass: 'knight',
    },
    blockCleric: {
        ...blockBase,
        id: 'blockCleric',
        characterClass: 'cleric',
    },
    blockRogue: {
        ...blockBase,
        id: 'blockRogue',
        characterClass: 'rogue',
    },
    blockWizard: {
        ...blockBase,
        id: 'blockWizard',
        characterClass: 'wizard',
    },
    swordSlash: {
        name: 'Sword Slash',
        energy: 1,
        id: 'swordSlash',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'strengthy = 0.5 * strength; chain(deal(strengthy), effect("bleed", 2))',
        type: 'attack',
        characterClass: 'knight',
    },
    parry: {
        name: 'Parry',
        energy: 1,
        id: 'parry',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'strengthy = 0.75 * strength; defensey = defense * .5; chain(deal(strengthy),addBlockToSelf(defensey))',
        type: 'attack',
        characterClass: 'knight',
    },
    berserk: {
        name: 'Berserk',
        energy: 1,
        id: 'berserk',
        targetNum: 1,
        targetType: 'self',
        actions: 'chain(effect("berserk",3), momentary())',
        type: 'enchantment',
        characterClass: 'rogue',
    },
    patientAmbush: {
        name: 'Patient Ambush',
        energy: 1,
        id: 'patientAmbush',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'queue(2, strengthy = strength * 2; ifStance("avoidant", dealFromStance("avoidant", strengthy)))',
        type: 'attack',
        characterClass: 'rogue',
    },
    stab: {
        name: 'Stab',
        energy: 1,
        id: 'stab',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'strengthy = strength + 6; chain(deal(strengthy), effect("bleed", 2))',
        type: 'attack',
        characterClass: 'rogue',
    },
    // catchTheKnife: {
    //     name: 'Catch The Knife',
    //     energy: 1,
    //     id: 'catchTheKnife',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions: 'effect("knifeCatcher", 1)', //todo
    //     type: 'enchantment',
    //     characterClass: 'rogue',
    // },
    // cowardlyTactics: {
    //     name: 'Cowardly Tactics',
    //     energy: 1,
    //     id: 'cowardlyTactics',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions: 'effect("cowardlyTactics", 1)', //todo
    //     type: 'enchantment',
    //     characterClass: 'rogue',
    // },
    // throwingKnife: {
    //     name: 'Throwing Knife',
    //     energy: 1,
    //     id: 'throwingKnife',
    //     targetNum: 1,
    //     targetType: 'enemies',
    //     actions:
    //         'strengthy = strength * .5; chain(deal(strengthy), ifKilled(returnCardToHand()))', //todo
    //     type: 'attack',
    //     characterClass: 'rogue',
    // },
    // retreatToTheShadows: {
    //     name: 'Retreat To The Shadows',
    //     energy: 1,
    //     id: 'retreatToTheShadows',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions: 'toStance("avoidant")', //todo
    //     type: 'utility',
    //     characterClass: 'rogue',
    // },
    poisonedBlade: {
        name: 'Poisoned Blade',
        energy: 1,
        id: 'poisonedBlade',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'strengthy = strength * .5; chain(deal(strengthy), effect("poison", 5))',
        type: 'utility',
        characterClass: 'rogue',
    },
    // exponentialIllness: {
    //     name: 'Exponential Illness',
    //     energy: 1,
    //     id: 'exponentialIllness',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions: 'exponentialIllness(3)', //todo
    //     type: 'utility',
    //     characterClass: 'rogue',
    // },
    // twistTheKnife: {
    //     name: 'Twist The Knife',
    //     energy: 1,
    //     id: 'twistTheKnife',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions:
    //         'strengthy1 = 1.25 * strength; strengthy2 = .75; chain(deal(strengthy1), ifHealth("less than", .5, deal(strengthy2)))', //todo
    //     type: 'attack',
    //     characterClass: 'rogue',
    // },
    // flashbang: {
    //     name: 'Flashbang',
    //     energy: 2,
    //     id: 'flashbang',
    //     targetNum: 'all',
    //     targetType: 'enemies',
    //     actions:
    //         'chain(effect("stunned", 1), effect("debilitated", 1), effect("unguarded", 1), momentary())', //todo
    //     type: 'attack',
    //     characterClass: 'rogue',
    // },
    // songOfCourage: {
    //     name: 'Song Of Courage',
    //     energy: 2,
    //     id: 'songOfCourage',
    //     targetNum: 1,
    //     targetType: 'self',
    //     actions: 'effect("melody", 2)', //todo
    //     type: 'enchantment',
    //     characterClass: 'bard',
    // },
    dutifulStab: {
        name: 'Dutiful Stab',
        energy: 1,
        id: 'dutifulStab',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'chain(deal(strength), ifFirstPlay(effect("debilitated",1)))',
        type: 'attack',
        characterClass: 'knight',
    },
    charge: {
        name: 'Charge',
        energy: 2,
        id: 'charge',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'chain(deal(strength), effect("vulnerable", 1))',
        type: 'attack',
        characterClass: 'knight',
    },
    testudoFormation: {
        name: 'Testudo Formation',
        energy: 1,
        id: 'testudoFormation',
        targetNum: 1,
        targetType: 'friends',
        // TODO: "You may only play this card if this character is in an avoidant stance."
        actions:
            'chain(addBlock(defense), effect("strongblock", 1, "friends"))',
        type: 'utility',
        characterClass: 'knight',
    },
    guidingBolt: {
        name: 'Guiding Bolt',
        energy: 2,
        id: 'guidingBolt',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'chain(deal(wisdom), effect("unguarded", 2))',
        type: 'attack',
        characterClass: 'cleric',
    },
    gnomeBomb: {
        name: 'Gnome Bomb',
        energy: 0,
        id: 'gnomeBomb',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'strengthywisdomy = strength * .5 + wisdom * .5; chain(deal(strengthywisdomy), dwindle())',
        type: 'attack',
        characterClass: 'rogue',
    },
    smite: {
        name: 'Smite',
        energy: 1,
        id: 'smite',
        targetNum: 1,
        targetType: 'enemies',
        actions: 'smite(wisdom, defense)',
        type: 'attack',
        characterClass: 'cleric',
    },
    bless: {
        name: 'Bless',
        energy: 2,
        id: 'bless',
        targetNum: 1,
        targetType: 'friends',
        actions: 'effect("strongblock", 2)',
        type: 'defense',
        characterClass: 'cleric',
    },
    // prayerOfGoodFortune: {
    //     name: 'Prayer of Good Fortune',
    //     energy: 0,
    //     id: 'prayerOfGoodFortune',
    //     targetNum: 1,
    //     targetType: [
    //         { type: 'friends' },
    //         {
    //             type: 'enemies',
    //             constraint: { key: 'health', comparator: '<=', value: 3 },
    //         },
    //     ],
    //     actions:
    //         'chain(targetSwitch(["friend", addBlock(3)], ["enemy", killIf(targetHealth < 4)]), momentary())',
    //     type: 'utility',
    //     characterClass: 'cleric',
    // },
    psychicWarfare: {
        name: 'Psychic Warfare',
        energy: 0,
        id: 'psychicWarfare',
        targetNum: 1,
        targetType: 'enemies',
        actions:
            'wisdomy1 = wisdom * .75; wisdomy2 = wisdom * .25; chain(psychicWarfare(wisdomy1,wisdomy2), dwindle())',
        type: 'attack',
        characterClass: 'wizard',
    },
    orbOfHolyLight: {
        name: 'Orb of Holy Light',
        energy: 2,
        id: 'orbOfHolyLight',
        targetNum: 1,
        targetType: 'self',
        actions: 'orb("holyLight", 3)',
        type: 'enchantment',
        characterClass: 'cleric',
    },
    mantraOfPatience: {
        name: 'Mantra of Patience',
        energy: 1,
        id: 'mantraOfPatience',
        targetNum: 1,
        targetType: 'self',
        actions: 'chain(queue(1, addEnergy(2)), momentary())',
        type: 'utility',
        characterClass: 'cleric',
    },
    helpingHand: {
        name: 'Helping Hand',
        energy: 1,
        id: 'helpingHand',
        targetNum: 1,
        targetType: 'friends',
        actions: 'chain(addBlock(defense + 2), addWisdom(2), addStrength(2))',
        type: 'utility',
        characterClass: 'cleric',
    },
}
