export const BUILD_VER = '1.0.2.0'
export const LEADERBOARD_ENTRIES_PER_PAGE = 5
export const LEADERBOARD_ENTRIES_TO_DISPLAY = 100
export const MAX_LEADERBOARD_PAGE =
    LEADERBOARD_ENTRIES_TO_DISPLAY / LEADERBOARD_ENTRIES_PER_PAGE
export const NUM_KAIJUS_IN_PARTY = 3
