export const BUILD_VER = '1.2.1.0'
export const LEADERBOARD_ENTRIES_PER_PAGE = 5
export const LEADERBOARD_ENTRIES_TO_DISPLAY = 100
export const MAX_LEADERBOARD_PAGE =
    LEADERBOARD_ENTRIES_TO_DISPLAY / LEADERBOARD_ENTRIES_PER_PAGE
export const TOP_PERCENTILE_CUTOFF = 0.20
export const NUM_KAIJUS_IN_PARTY = 3
export const MAX_USERNAME_LENGTH = 20
export const MIN_USERNAME_LENGTH = 3
export const ARBITRUM_CHAIN_ID = 42161
export const AUTH_EXPIRATION_TIME = '1d'
