export type CharacterName =
    | 'bloatDemon'
    | 'bogSpirit'
    | 'bookle'
    | 'bumbit'
    | 'frogKnight'
    | 'frogWizard'
    | 'gnomeHooligan'
    | 'goblinDragon'
    | 'greenJester'
    | 'jerry'
    | 'lichLord'
    | 'mushroomFarmer'
    | 'notoriousBEAN'
    | 'penguinKnight'
    | 'skeletonWarrior'
    | 'snacky'
    | 'theHatefly'
    | 'trioOfFools'
    | 'warhog'
    | 'wimpyGuard'
    | EnemyCharacterName

export type EnemyCharacterName =
    | 'skeletonWarrior'
    | 'matchaGelatinCube'
    | 'mimic'
    | 'orcWarrior'
    | 'bosshogJurgen'
    | 'toadmaw'
    | 'cultist'
    | 'halfdan'
export type DungeonName =
    | 'Skelepit Dungeon'
    | 'Hooligan’s Bluff'
    | 'The Matcha Caves'
    | 'Fort Skeleton'
    | 'The Ninth Trash Hole of Hell'

export type StanceName = 'defensive' | 'neutral' | 'aggressive'
export type PileId = 'draw' | 'hand' | 'discard' | 'removedRoom' | 'removedRun'
