import type { CharacterName, CharacterStats } from 'shared'

const unknownEnemyFiller = {
    class: 'knight',
    constitution: 100,
    strength: 20,
    wisdom: 5,
    dexterity: 5,
} as const

export const statsMap: Record<CharacterName, CharacterStats> = {
    bloatDemon: {
        name: 'bloatDemon',
        displayName: 'Bloat Demon',
        isPc: true,
        class: 'knight',

        constitution: 160,
        strength: 27,
        wisdom: 5,
        dexterity: 5,
    },
    bogSpirit: {
        name: 'bogSpirit',
        displayName: 'Bog Spirit',
        isPc: true,
        class: 'knight',

        constitution: 224,
        strength: 16,
        wisdom: 5,
        dexterity: 5,
    },
    bookle: {
        name: 'bookle',
        displayName: 'Bookle',
        isPc: true,
        class: 'knight',

        constitution: 60,
        strength: 10,
        wisdom: 5,
        dexterity: 5,
    },
    bumbit: {
        name: 'bumbit',
        displayName: 'Bumbit',
        isPc: true,
        class: 'knight',

        constitution: 58,
        strength: 18,
        wisdom: 5,
        dexterity: 5,
    },
    frogKnight: {
        name: 'frogKnight',
        displayName: 'Frog Knight',
        isPc: true,
        class: 'knight',

        constitution: 72,
        strength: 8,
        wisdom: 5,
        dexterity: 5,
    },
    frogWizard: {
        name: 'frogWizard',
        displayName: 'Frog Wizard',
        isPc: true,
        class: 'knight',

        constitution: 66,
        strength: 24,
        wisdom: 5,
        dexterity: 5,
    },
    gnomeHooligan: {
        name: 'gnomeHooligan',
        displayName: 'Gnome Hooligan',
        isPc: true,
        class: 'knight',

        constitution: 43,
        strength: 14,
        wisdom: 5,
        dexterity: 5,
    },
    goblinDragon: {
        name: 'goblinDragon',
        displayName: 'Goblin Dragon',
        isPc: true,
        class: 'knight',

        constitution: 120,
        strength: 13,
        wisdom: 5,
        dexterity: 5,
    },
    greenJester: {
        name: 'greenJester',
        displayName: 'Green Jester',
        isPc: true,
        class: 'knight',

        constitution: 120,
        strength: 34,
        wisdom: 5,
        dexterity: 5,
    },
    jerry: {
        name: 'jerry',
        displayName: 'Jerry',
        isPc: true,
        class: 'knight',

        constitution: 86,
        strength: 19,
        wisdom: 5,
        dexterity: 5,
    },
    lichLord: {
        name: 'lichLord',
        displayName: 'Lich Lord',
        isPc: true,
        class: 'knight',

        constitution: 250,
        strength: 27,
        wisdom: 5,
        dexterity: 5,
    },
    matchaGelatinCube: {
        name: 'matchaGelatinCube',
        displayName: 'Matcha Gelatin Cube',
        isPc: false,
        class: 'knight',

        constitution: 78,
        strength: 7,
        wisdom: 5,
        dexterity: 5,
    },
    mimic: {
        name: 'mimic',
        displayName: 'Mimic',
        isPc: false,
        class: 'knight',

        constitution: 130,
        strength: 12,
        wisdom: 5,
        dexterity: 5,
    },
    mushroomFarmer: {
        name: 'mushroomFarmer',
        displayName: 'Mushroom Farmer',
        isPc: true,
        class: 'cleric',

        constitution: 112,
        strength: 8,
        wisdom: 9,
        dexterity: 6,
    },
    notoriousBEAN: {
        name: 'notoriousBEAN',
        displayName: 'Notorious B.E.A.N',
        isPc: true,
        class: 'knight',

        constitution: 75,
        strength: 14,
        wisdom: 5,
        dexterity: 5,
    },
    orcWarrior: {
        name: 'orcWarrior',
        displayName: 'Orc Warrior',
        isPc: false,
        class: 'knight',

        constitution: 88,
        strength: 12,
        wisdom: 5,
        dexterity: 5,
    },
    penguinKnight: {
        name: 'penguinKnight',
        displayName: 'Penguin Knight',
        isPc: true,
        class: 'knight',
        constitution: 66,
        strength: 9,
        wisdom: 5,
        dexterity: 5,
    },
    skeletonWarrior: {
        name: 'skeletonWarrior',
        displayName: 'Skeleton Warrior',
        isPc: false,
        class: 'knight',

        constitution: 10,
        strength: 2,
        wisdom: 5,
        dexterity: 5,
    },
    snacky: {
        name: 'snacky',
        displayName: 'Snacky',
        isPc: true,
        class: 'knight',

        constitution: 67,
        strength: 16,
        wisdom: 5,
        dexterity: 5,
    },
    theHatefly: {
        name: 'theHatefly',
        displayName: 'The Hatefly',
        isPc: true,
        class: 'knight',

        constitution: 300,
        strength: 22,
        wisdom: 5,
        dexterity: 5,
    },
    trioOfFools: {
        name: 'trioOfFools',
        displayName: 'Trio of Fools',
        isPc: true,
        class: 'knight',

        constitution: 110,
        strength: 15,
        wisdom: 5,
        dexterity: 5,
    },
    warhog: {
        name: 'warhog',
        displayName: 'Warhog',
        isPc: true,
        class: 'knight',

        constitution: 84,
        strength: 6,
        wisdom: 5,
        dexterity: 5,
    },
    wimpyGuard: {
        name: 'wimpyGuard',
        displayName: 'Wimpy Guard',
        isPc: true,
        class: 'knight',

        constitution: 170,
        strength: 24,
        wisdom: 5,
        dexterity: 5,
    },
    bosshogJurgen: {
        name: 'bosshogJurgen',
        displayName: 'bosshogJurgen',
        isPc: false,
        ...unknownEnemyFiller,
    },
    toadmaw: {
        name: 'toadmaw',
        displayName: 'toadmaw',
        isPc: false,
        ...unknownEnemyFiller,
    },
    cultist: {
        name: 'cultist',
        displayName: 'cultist',
        isPc: false,
        ...unknownEnemyFiller,
    },
    halfdan: {
        name: 'halfdan',
        displayName: 'halfdan',
        isPc: false,
        ...unknownEnemyFiller,
    },
}
