import type { CharacterName, CharacterStats } from 'shared'
export const statsMap: Record<CharacterName, CharacterStats> = {
    bloatDemon: {
        name: 'bloatDemon',
        displayName: 'Bloat Demon',
        isPc: true,
        class: 'knight',

        constitution: 160,
        strength: 27,
        magic: 5,
        dexterity: 5,
    },
    bogSpirit: {
        name: 'bogSpirit',
        displayName: 'Bog Spirit',
        isPc: true,
        class: 'knight',

        constitution: 224,
        strength: 16,
        magic: 5,
        dexterity: 5,
    },
    bookle: {
        name: 'bookle',
        displayName: 'Bookle',
        isPc: true,
        class: 'knight',

        constitution: 60,
        strength: 10,
        magic: 5,
        dexterity: 5,
    },
    bumbit: {
        name: 'bumbit',
        displayName: 'Bumbit',
        isPc: true,
        class: 'knight',

        constitution: 58,
        strength: 18,
        magic: 5,
        dexterity: 5,
    },
    frogKnight: {
        name: 'frogKnight',
        displayName: 'Frog Knight',
        isPc: true,
        class: 'knight',

        constitution: 72,
        strength: 8,
        magic: 5,
        dexterity: 5,
    },
    frogWizard: {
        name: 'frogWizard',
        displayName: 'Frog Wizard',
        isPc: true,
        class: 'knight',

        constitution: 66,
        strength: 24,
        magic: 5,
        dexterity: 5,
    },
    gnomeHooligan: {
        name: 'gnomeHooligan',
        displayName: 'Gnome Hooligan',
        isPc: true,
        class: 'knight',

        constitution: 43,
        strength: 14,
        magic: 5,
        dexterity: 5,
    },
    goblinDragon: {
        name: 'goblinDragon',
        displayName: 'Goblin Dragon',
        isPc: true,
        class: 'knight',

        constitution: 120,
        strength: 13,
        magic: 5,
        dexterity: 5,
    },
    greenJester: {
        name: 'greenJester',
        displayName: 'Green Jester',
        isPc: true,
        class: 'knight',

        constitution: 120,
        strength: 34,
        magic: 5,
        dexterity: 5,
    },
    jerry: {
        name: 'jerry',
        displayName: 'Jerry',
        isPc: true,
        class: 'knight',

        constitution: 86,
        strength: 19,
        magic: 5,
        dexterity: 5,
    },
    lichLord: {
        name: 'lichLord',
        displayName: 'Lich Lord',
        isPc: true,
        class: 'knight',

        constitution: 250,
        strength: 27,
        magic: 5,
        dexterity: 5,
    },
    matchaGelatinCube: {
        name: 'matchaGelatinCube',
        displayName: 'Matcha Gelatin Cube',
        isPc: false,
        class: 'knight',

        constitution: 78,
        strength: 7,
        magic: 5,
        dexterity: 5,
    },
    mimic: {
        name: 'mimic',
        displayName: 'Mimic',
        isPc: false,
        class: 'knight',

        constitution: 130,
        strength: 12,
        magic: 5,
        dexterity: 5,
    },
    mushroomFarmer: {
        name: 'mushroomFarmer',
        displayName: 'Mushroom Farmer',
        isPc: true,
        class: 'bard',

        constitution: 112,
        strength: 8,
        magic: 9,
        dexterity: 6,
    },
    notoriousBEAN: {
        name: 'notoriousBEAN',
        displayName: 'Notorious B.E.A.N',
        isPc: true,
        class: 'knight',

        constitution: 75,
        strength: 14,
        magic: 5,
        dexterity: 5,
    },
    orcWarrior: {
        name: 'orcWarrior',
        displayName: 'Orc Warrior',
        isPc: false,
        class: 'knight',

        constitution: 88,
        strength: 12,
        magic: 5,
        dexterity: 5,
    },
    penguinKnight: {
        name: 'penguinKnight',
        displayName: 'Penguin Knight',
        isPc: true,
        class: 'knight',
        constitution: 66,
        strength: 9,
        magic: 5,
        dexterity: 5,
    },
    skeletonWarrior: {
        name: 'skeletonWarrior',
        displayName: 'Skeleton Warrior',
        isPc: false,
        class: 'wizard',

        constitution: 10,
        strength: 2,
        magic: 5,
        dexterity: 5,
    },
    snacky: {
        name: 'snacky',
        displayName: 'Snacky',
        isPc: true,
        class: 'knight',

        constitution: 67,
        strength: 16,
        magic: 5,
        dexterity: 5,
    },
    theHatefly: {
        name: 'theHatefly',
        displayName: 'The Hatefly',
        isPc: true,
        class: 'knight',

        constitution: 300,
        strength: 22,
        magic: 5,
        dexterity: 5,
    },
    trioOfFools: {
        name: 'trioOfFools',
        displayName: 'Trio of Fools',
        isPc: true,
        class: 'knight',

        constitution: 110,
        strength: 15,
        magic: 5,
        dexterity: 5,
    },
    warhog: {
        name: 'warhog',
        displayName: 'Warhog',
        isPc: true,
        class: 'knight',

        constitution: 84,
        strength: 6,
        magic: 5,
        dexterity: 5,
    },
    wimpyGuard: {
        name: 'wimpyGuard',
        displayName: 'Wimpy Guard',
        isPc: true,
        class: 'knight',

        constitution: 170,
        strength: 24,
        magic: 5,
        dexterity: 5,
    },
}
