import type { Cards, OwnedCharacter } from '@shared'

export function makeCards(
    chosen: OwnedCharacter[] = [],
    _username: string
): Cards {
    const characterUid = chosen[0].uid
    return {
        draw: {
            uuid11: {
                name: 'Shield',
                energy: 1,
                id: 'cardShield',
                targetNum: 1,
                targetType: 'friends',
                actions: 'block(dexterity + 2)',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid12: {
                name: 'Shield',
                energy: 1,
                id: 'cardShield',
                targetNum: 1,
                targetType: 'friends',
                actions: 'block(dexterity + 2)',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid21: {
                name: 'Shield',
                energy: 1,
                id: 'cardShield',
                targetNum: 1,
                targetType: 'friends',
                actions: 'block(dexterity + 2)',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid22: {
                name: 'Shield of Light',
                energy: 1,
                id: 'cardShieldOfLight',
                targetNum: 1,
                targetType: 'friends',
                actions: 'block(magic + 3)',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid23: {
                name: 'Shield of Light',
                energy: 1,
                id: 'cardShieldOfLight',
                targetNum: 1,
                targetType: 'friends',
                actions: 'block(magic + 3)',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid24: {
                name: 'Sweep The Leg',
                energy: 2,
                id: 'cardSweepTheLeg',
                targetNum: 1,
                targetType: 'enemies',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid25: {
                name: 'Sweep The Leg',
                energy: 2,
                id: 'cardSweepTheLeg',
                targetNum: 1,
                targetType: 'enemies',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
        hand: {
            uuid26: {
                name: 'Sweep The Leg',
                energy: 2,
                id: 'cardSweepTheLeg',
                targetNum: 1,
                targetType: 'enemies',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
        discard: {},
        removed: {
            uuid3: {
                name: 'Sweep The Leg',
                energy: 2,
                id: 'cardSweepTheLeg',
                targetNum: 1,
                targetType: 'enemies',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
    }
}
