import type { Cards, OwnedCharacter } from '@shared'

export function makeCards(
    chosen: OwnedCharacter[] = [],
    _username: string
): Cards {
    const characterUid = chosen[0].uid
    return {
        draw: {
            uuid11: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid12: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
        hand: {
            uuid21: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid22: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid23: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid24: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid25: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid26: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid27: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid28: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid29: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid210: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid211: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
            uuid212: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
        discard: {
            uuid3: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
        removed: {
            uuid3: {
                name: 'Sweep The Leg',
                energy: 2,
                url: './Sweep The Leg.png',
                actions: 'chain(deal(strength), debilitate(1))',
                text: ['string'],
                definitions: ['string'],
                type: 'string',
                characterUid,
                characterClass: 'string',
                deckId: 'string',
            },
        },
    }
}
